server:
  port: 7072

http:
  client:
    config:
      timeout: 30000
      socket_timeout: 30000

auth:
  oauth2:
    serverUrl: ###
    clientId: ###
    clientSecret: ###

fetching:
  pool-size: 4
  fetching-task-properties:
    -
      description: mosi-pt1h-csv-fetch
      request:
        "https://point-forecast.weather.mg/search?\
        locatedAt=6.8833,52.7333\
        &validFrom=2018-06-25T00:00:00Z\
        &validUntil=2018-07-05T23:00:00Z\
        &fields=\
        meteoGroupStationId,\
        airTemperatureInCelsius,\
        relativeHumidityInPercent,\
        precipitationProbabilityInPercent,\
        precipitationAmountInMillimeter,\
        windDirectionInDegree,\
        windSpeedInMeterPerSecond,\
        globalRadiationInJoulePerSquareCentimeter,\
        cloudCoverLowerThan5000MeterInOcta\
        &validPeriod=PT1H"
      directory: fetched_data
      file-prefix: mosi_api_csv_snapshots_pt1h
      filename-format: snapshot-{yyyy-MM-dd-HH-mm-ssZZ}
      source-content-type: json
      target-content-type: csv
      frequency: "* * * * * *"
#      frequency: 0 0,10,20,30,40,50 * * * *
    -
      description: mosi-pt1h-json-fetch
      request:
        "https://point-forecast.weather.mg/search?\
        locatedAt=6.8833,52.7333\
        &validFrom=2018-06-25T00:00:00Z\
        &validUntil=2018-07-05T23:00:00Z\
        &fields=\
        meteoGroupStationId,\
        airTemperatureInCelsius,\
        relativeHumidityInPercent,\
        precipitationProbabilityInPercent,\
        precipitationAmountInMillimeter,\
        windDirectionInDegree,\
        windSpeedInMeterPerSecond,\
        globalRadiationInJoulePerSquareCentimeter,\
        cloudCoverLowerThan5000MeterInOcta\
        &validPeriod=PT1H"
      directory: fetched_data
      file-prefix: mosi_api_json_snapshots_pt1h
      filename-format: snapshot-{yyyy-MM-dd-HH-mm-ssZZ}
      source-content-type: json
      target-content-type: json
      frequency: "* * * * * *"
#      frequency: 0 0,10,20,30,40,50 * * * *
    -
      description: mosi-pt0s-csv-fetch
      request:
        "https://point-forecast.weather.mg/search?\
        locatedAt=6.8833,52.7333\
        &validFrom=2018-06-25T00:00:00Z\
        &validUntil=2018-07-05T23:00:00Z\
        &fields=\
        meteoGroupStationId,\
        airTemperatureInCelsius,\
        relativeHumidityInPercent,\
        precipitationProbabilityInPercent,\
        precipitationAmountInMillimeter,\
        windDirectionInDegree,\
        windSpeedInMeterPerSecond,\
        globalRadiationInJoulePerSquareCentimeter,\
        cloudCoverLowerThan5000MeterInOcta\
        &validPeriod=PT0S"
      directory: fetched_data
      file-prefix: mosi_api_csv_snapshots_pt0s
      filename-format: snapshot-{yyyy-MM-dd-HH-mm-ssZZ}
      source-content-type: json
      target-content-type: csv
      frequency: "* * * * * *"
#      frequency: 0 0,10,20,30,40,50 * * * *
    -
      description: mosi-pt0s-json-fetch
      request:
        "https://point-forecast.weather.mg/search?\
        locatedAt=6.8833,52.7333\
        &validFrom=2018-06-25T00:00:00Z\
        &validUntil=2018-07-05T23:00:00Z\
        &fields=\
        meteoGroupStationId,\
        airTemperatureInCelsius,\
        relativeHumidityInPercent,\
        precipitationProbabilityInPercent,\
        precipitationAmountInMillimeter,\
        windDirectionInDegree,\
        windSpeedInMeterPerSecond,\
        globalRadiationInJoulePerSquareCentimeter,\
        cloudCoverLowerThan5000MeterInOcta\
        &validPeriod=PT0S"
      directory: fetched_data
      file-prefix: mosi_api_json_snapshots_pt0s
      filename-format: snapshot-{yyyy-MM-dd-HH-mm-ssZZ}
      source-content-type: json
      target-content-type: json
      frequency: "* * * * * *"
#      frequency: 0 0,10,20,30,40,50 * * * *
